"""The Alaap and TrenTorch study plan, as data.

One linear sequence of stages. Each stage says what you can do after it, why it
matters for Alaap, and pulls in:
    alaap     sections of the Alaap study guide, by anchor (part-0, s2-1, ...), quoted
    tt        TrenTorch modules, by number, read from E:/TrenTorch at build time
    arch      Alaap architecture diagrams: inline to draw here, chips to link
    diagram   a diagram drawn for this stage (DIAGRAMS below)
    accel     Accelerate sessions that practise it, as (label, route)
    map       the node on Accelerate's map of the work ahead
    unlocks   the TrenTorch historical milestone it opens
    check     one exit question with a short model answer

Milestones follow ROADMAP-AHEAD.md: milestone 1 caps Alaap at four hours (Part 0
and the physics half of Part 2), milestone 2 is TrenTorch as the spine with Part 1,
the rest of Part 2 and Part 3, milestone 3 is Parts 4 to 7, inference, and the
from-scratch artifact. TrenTorch hours are an estimate of about 1.5 hours a module.
"""

MILESTONES = [
    {"id": 1, "name": "Milestone 1 · Primitives", "when": "21 Sep to 25 Oct 2026",
     "note": "Alaap is capped at four hours here: orientation and the physics half of Part 2. Everything else in this milestone is systems and mathematics."},
    {"id": 2, "name": "Milestone 2 · Mechanism", "when": "late Oct to mid Dec 2026, roughly",
     "note": "TrenTorch is the spine: you build the framework, then read real PyTorch without guessing. Speaker identity becomes readable once the mathematics is there."},
    {"id": 3, "name": "Milestone 3 · Training", "when": "first quarter of 2027, roughly",
     "note": "How TTS actually works, description to voice, evaluation, making it run, and Alaap as something you trained rather than assembled."},
]

TT_HOURS = 1.5

STAGES = [
    # ------------------------------------------------------------------ milestone 1
    {"n": 0, "ms": 1, "title": "Orientation: what Alaap is, and run it", "hours": 2,
     "goal": "Describe what Alaap does in one breath, run it, and listen to what it makes.",
     "why": "Everything after this is detail hung on one idea: a frozen TTS model driven by a learned speaker vector. Hold that shape before any of the detail.",
     "alaap": ["part-0"], "arch_inline": ["ctx"], "arch": ["tower", "mint", "render", "gates"],
     "accel": [("Week 1, Part 0: orientation", "index.html#/s/1/3")], "map": "Part 0, orientation",
     "check": ("Why is the TTS model never trained, and what would break if it were?",
               "All the learning lives in the mapper, which produces a vector the frozen model already knows how to consume. Train the TTS and the vector space moves under every stored identity, so every minted voice drifts, and the independent drift and consistency judges stop meaning anything.")},
    {"n": 1, "ms": 1, "title": "Sound as data: sampling and Nyquist", "hours": 2,
     "goal": "Say what a sample rate buys you, find the Nyquist cliff on a real spectrum, and explain why analysing audio at the wrong rate moves every frequency.",
     "why": "Alaap's audio lives at four sample rates: corpus 24 kHz, WavLM 16 kHz, MioCodec 44.1 kHz, Sarvam 22.05 kHz. Mixing them up once reversed an experiment's result.",
     "alaap": ["part-2", "s2-1"], "diagram": "sampling",
     "accel": [("Week 3, Sampling and Nyquist", "index.html#/s/3/3")], "map": "Sampling and Nyquist",
     "check": ("A clip recorded at 24 kHz is resampled to 16 kHz. What happens to a component at 10 kHz, and why?",
               "It is removed. At 16 kHz the Nyquist limit is 8 kHz, so the resampler's low-pass filter cuts everything above it; without that filter the 10 kHz energy would alias down to 6 kHz. That is the cliff you find on the plot.")},
    {"n": 2, "ms": 1, "title": "Source and filter: what describes a voice", "hours": 3,
     "goal": "Separate the glottal buzz (F0) from the vocal-tract tube (formants), and map each of Alaap's measurements onto one side or the other.",
     "why": "Alaap's identity axes are exactly this split: f0_mean measures the source, vtl_cm and the formants measure the filter, and spectral_tilt was meant to measure the source's shape but partly reads pitch.",
     "alaap": ["s2-3"], "diagram": "sourcefilter", "arch": ["axes"],
     "accel": [("Week 5, The source-filter model", "index.html#/s/5/3")], "map": "The source-filter model",
     "check": ("Two recordings of the same person, one speaking and one singing higher. Which measurements should move, and which should not?",
               "The source moves: F0 goes up. The filter should not: vocal-tract length and the formant pattern belong to the tube, which is the same person. A measurement that moves with F0 when it claims to measure the tube, as spectral tilt partly did, is confounded.")},

    # ------------------------------------------------------------------ milestone 2
    {"n": 3, "ms": 2, "title": "Tensors, built by hand", "tt": [1],
     "goal": "Build a Tensor class on NumPy and predict the shape, dtype and memory of any operation before running it.",
     "why": "Every model file in Alaap is tensor shapes. Reading one without guessing starts with having built the thing yourself.",
     "alaap": ["part-1", "s1-1"], "diagram": "tensor",
     "accel": [("Week 3, Vectors and matrices: shapes by hand", "index.html#/s/3/2")], "map": "Tensors",
     "check": ("A (32, 1, 80) tensor is added to an (80,) tensor. What is the result's shape, and what did broadcasting do?",
               "(32, 1, 80). The (80,) tensor is treated as (1, 1, 80) and virtually repeated along the first two axes without copying memory, then added element by element.")},
    {"n": 4, "ms": 2, "title": "Activations and layers", "tt": [2, 3],
     "goal": "Build Linear, ReLU, softmax and dropout as modules, and say what each one's parameters and buffers are.",
     "why": "nn.Module, train() and eval() appear in every Alaap experiment. Dropout is the simplest thing that behaves differently in the two modes.",
     "alaap": ["s1-3"], "diagram": "layer", "unlocks": ["01", "02"], "map": "Modules and parameters",
     "check": ("Dropout with p = 0.5 scales surviving activations by 2 during training. What does it do at eval time, and why the scaling?",
               "Nothing: at eval every unit passes through unscaled. Scaling by 1/(1-p) during training keeps the expected activation the same in both modes, so the next layer sees the same magnitudes whether or not dropout is on.")},
    {"n": 5, "ms": 2, "title": "Losses: measuring how wrong", "tt": [4],
     "goal": "Build MSE and cross-entropy, compute softmax stably, and say why cross-entropy's gradient survives where squared error's saturates.",
     "why": "Negative log-likelihood is the loss the mixture density network in stage 17 trains on, and cross-entropy is its one-component cousin.",
     "diagram": "loss", "map": "Why cross-entropy survives",
     "accel": [("Week 1, Functions, exponentials, logarithms: negative log-likelihood", "index.html#/s/1/2"),
               ("Week 5, Probability: softmax and cross-entropy", "index.html#/s/5/2")],
     "check": ("With softmax and cross-entropy together, what is the gradient with respect to the logits?",
               "p minus the one-hot target. It stays large while the prediction is wrong, however confident, which is why this pairing does not stall the way sigmoid plus squared error does.")},
    {"n": 6, "ms": 2, "title": "The data pipeline", "tt": [5],
     "goal": "Build a Dataset and a DataLoader that shuffle, batch and collate, and reason about what a batch costs in memory.",
     "why": "Alaap streams clips from corpora it never downloads whole. How data reaches the model decides what an experiment can afford.",
     "diagram": "data",
     "check": ("Samples are stored ordered by speaker. What goes wrong if you train without shuffling?",
               "Each batch holds one speaker, so gradients chase that speaker and then the next: training oscillates, and the model forgets earlier speakers. Shuffling makes each batch a fair sample of the whole set.")},
    {"n": 7, "ms": 2, "title": "Autograd: the gradient engine", "tt": [6],
     "goal": "Build reverse-mode automatic differentiation: record the forward pass as a graph, then walk it backward with each operation's gradient rule.",
     "why": "Knowing exactly what backward() does, and what no_grad() and detach() switch off, is Part 1's promise. This is where it is earned.",
     "alaap": ["s1-2"], "diagram": "autograd", "map": "Autograd",
     "accel": [("Week 4, Gradients and descent: backprop by hand", "index.html#/s/4/2"),
               ("Week 2, Derivatives, properly: the chain rule", "index.html#/s/2/2")],
     "check": ("y = x @ W. Given the gradient of the loss with respect to y, what are the gradients for x and W?",
               "grad_x = grad_y @ W.T and grad_W = x.T @ grad_y. Two matmuls backward for one forward, which is why the backward pass costs roughly twice the forward.")},
    {"n": 8, "ms": 2, "title": "Optimisers and the training loop", "tt": [7, 8],
     "goal": "Build SGD and Adam, write the full loop (zero_grad, forward, loss, backward, step), and train a network from scratch while explaining every line.",
     "why": "This is milestone 2's gate: a small network trained from scratch with every line and every gradient explained.",
     "alaap": ["s1-4"], "diagram": "loop", "unlocks": ["03"], "map": "The training loop",
     "check": ("What happens if you forget zero_grad() between steps?",
               "Gradients accumulate across steps, so each update applies the sum of every previous gradient: steps grow and training diverges. Accumulation is useful on purpose, for a large effective batch, but only when you zero it every N steps.")},
    {"n": 9, "ms": 2, "title": "The same things, in real PyTorch", "hours": 3,
     "goal": "Map every TrenTorch piece to its PyTorch name, and pass Part 1's exit checklist on a real Alaap model: WavLM's hidden states.",
     "why": "TrenTorch taught the mechanism; Alaap is written in PyTorch. This stage closes that gap, including the lesson that out-of-memory is sometimes system RAM, not VRAM.",
     "alaap": ["s1-5"], "diagram": "torchmap", "map": "Part 1's exit checklist",
     "check": ("model.eval() and torch.no_grad() are both used in every Alaap experiment. What does each switch off?",
               "eval() changes layer behaviour: dropout stops dropping and batch norm uses its running statistics. no_grad() stops recording the graph, so no activations are kept for backward and memory falls. They are independent, and inference wants both.")},
    {"n": 10, "ms": 2, "title": "Convolutions, and batch normalisation", "tt": [9], "unlocks": ["04"],
     "goal": "Build Conv2d, pooling and BatchNorm2d, and see a convolution as one small filter slid along an axis.",
     "why": "ECAPA-TDNN, Alaap's independent identity judge, is one-dimensional convolution along time over audio frames, with dilation, then attentive pooling. The mechanism is this module's.",
     "diagram": "conv1d", "map": "Batch normalisation",
     "check": ("Batch normalisation has two separate effects. Name them.",
               "It normalises each channel's activations to zero mean and unit variance using the batch, which steadies and speeds up training. And because batch statistics are noisy, it adds a regularising noise. At eval it swaps batch statistics for running ones, which is why eval() matters.")},
    {"n": 11, "ms": 2, "title": "The rest of sound: frequency, and how estimators lie", "hours": 7,
     "goal": "Read a spectrogram's time and frequency resolution from its parameters, and read alaap/acoustics.py saying what each function measures and how it can be wrong.",
     "why": "Every attribute Alaap captions is produced by these estimators. If measure() is wrong, the caption, the mapper and the adherence score are all wrong together and nothing complains.",
     "alaap": ["s2-2", "s2-4"], "diagram": "stft", "arch": ["axes", "rev"],
     "check": ("At 24 kHz with n_fft = 2048 and hop 512, what are the frequency and time resolutions?",
               "Frequency: 24000 / 2048, about 11.7 Hz per bin. Time: 512 / 24000, about 21 ms between frames, with each window 85 ms long. Finer frequency costs blurrier time, and the reverse.")},
    {"n": 12, "ms": 2, "title": "Speaker identity: embeddings that recognise people", "hours": 5,
     "goal": "Explain how a speaker embedding is made, why it is invariant to channel, and why verification thresholds must be fitted in-domain.",
     "why": "ECAPA is trained to ignore channel and quality, so it can recognise you down a bad line. That is exactly why Alaap uses it as the independent judge for identity and never for quality.",
     "alaap": ["part-3", "s3-1", "s3-2"], "diagram": "xvector", "arch": ["mods"], "map": "Part 3, speaker identity",
     "accel": [("Week 3, Vectors and matrices: cosine similarity", "index.html#/s/3/2"),
               ("Week 4, Embeddings and attention: where embeddings come from", "index.html#/s/4/3")],
     "check": ("Why does fitting C_same and C_diff in-domain halve the equal error rate?",
               "Cosine scores depend on the corpus, channel and language. A threshold from a paper sits in the wrong place for Alaap's audio, so it trades errors badly; fitted on Alaap's own same-speaker and different-speaker pairs, it sits where the two distributions actually cross.")},
    {"n": 13, "ms": 2, "title": "Is the space navigable?", "hours": 5,
     "goal": "Argue, from three papers, that a speaker embedding space can be sampled and interpolated, and say what goes wrong in sparse regions and past the shell.",
     "why": "This is the intellectual core of the project: if the space could not be navigated, Tower A would not be worth training.",
     "alaap": ["s3-3", "s3-4"], "arch_inline": ["geom"], "arch": ["tower"], "map": "The navigability papers",
     "accel": [("Week 3, Vectors and matrices: eigenvectors", "index.html#/s/3/2")],
     "check": ("Why SLERP rather than linear interpolation between two speaker vectors?",
               "Real speakers sit on a shell at roughly constant norm. A straight line between two points on a sphere cuts inside it, where the norm shrinks and the voice drifts toward the average. SLERP stays on the shell.")},
    {"n": 14, "ms": 2, "title": "Tokens and embeddings", "tt": [10, 11],
     "goal": "Build a character and a BPE tokenizer, an embedding table, and positional encodings, and say where the embedding numbers physically come from.",
     "why": "Modern TTS turns audio into tokens with a codec and generates them with a language model. The tokens are different; the machinery is this.",
     "diagram": "embed", "map": "Embeddings as weights",
     "accel": [("Week 4, Embeddings and attention", "index.html#/s/4/3")],
     "check": ("Where do the numbers in an embedding table come from?",
               "They are ordinary weights: a (vocabulary x dimension) matrix, initialised randomly and updated by gradient descent. Looking up a token is selecting a row, which is the same as multiplying a one-hot vector by the matrix.")},
    {"n": 15, "ms": 2, "title": "Attention and transformers", "tt": [12, 13], "unlocks": ["05"],
     "goal": "Build scaled dot-product and multi-head attention, then a full transformer block, and generate text with it.",
     "why": "WavLM and Alaap's acoustic language model are transformers. Their layers are why which WavLM layer you pool changes what you measure.",
     "diagram": "attention", "map": "Attention, derived",
     "accel": [("Week 4, Embeddings and attention: Q, K, V and the square root of d_k", "index.html#/s/4/3")],
     "check": ("Why divide QK^T by the square root of d_k?",
               "With unit-variance entries, a dot product of d_k terms has variance d_k, so scores grow with dimension. Large scores push softmax into saturation where its gradients vanish. Dividing by the square root of d_k keeps the variance near one.")},

    # ------------------------------------------------------------------ milestone 3
    {"n": 16, "ms": 3, "title": "How a TTS model actually works", "hours": 10,
     "goal": "Read the model card of any open TTS system and predict whether it can serve Alaap's architecture.",
     "why": "Codecs turn audio into integers, which is why modern TTS is a language model, and why Alaap can decode forty voices for the price of one.",
     "alaap": ["part-4", "s4-1", "s4-2", "s4-3", "s4-4"], "diagram": "ttslm", "arch_inline": ["codec"],
     "arch": ["backend", "render", "tower"], "map": "Parts 4 to 6",
     "check": ("Two FSQ codecs both use levels [8, 8, 8, 5, 5]. Why can you not feed one's tokens to the other's decoder?",
               "Equal levels give the same 12,800 valid indices but not the same meaning: each codec learned its own mapping from index to sound. Every index is accepted and nothing raises, so you get fluent speech saying different words.")},
    {"n": 17, "ms": 3, "title": "Description to voice", "hours": 5,
     "goal": "Read the mapper code and the paper it copies, and explain why the mapper blends top_k = 2 anchors.",
     "why": "One description corresponds to many valid voices. A mixture density network predicts a family rather than a point, and it is stage S3 of Alaap's plan, never started.",
     "alaap": ["part-5", "s5-1", "s5-2", "s5-3"], "diagram": "mdn", "arch_inline": ["mint"], "arch": ["dir"],
     "map": "Mathematics, applied",
     "accel": [("Week 1, negative log-likelihood", "index.html#/s/1/2"), ("Week 5, softmax as a distribution", "index.html#/s/5/2")],
     "check": ("Why an MDN rather than a regressor that predicts one speaker vector?",
               "Trained with squared error on a one-to-many mapping, a regressor predicts the average of every valid voice, which is a blurred central voice. An MDN predicts mixture weights, means and spreads, so sampling gives distinct plausible voices.")},
    {"n": 18, "ms": 3, "title": "Evaluation, and why most of it is wrong", "hours": 5,
     "goal": "Design a measurement that will not fool you: the right diversity statistic, the right judge, and a listening test with its discard rule written first.",
     "why": "This part has the highest ratio of hard-won knowledge to published literature in the whole project.",
     "alaap": ["part-6", "s6-1", "s6-2", "s6-3", "s6-4"], "diagram": "vendi", "arch_inline": ["gates"], "arch": ["rev", "exp"],
     "check": ("Why would a MOS predictor make a bad naturalness gate for Alaap?",
               "DNSMOS correlates with mean pitch at r = -0.788 where humans correlate at -0.059, so it systematically rejects high-pitched voices for a reason people do not share, fighting the diversity the project exists to create.")},
    {"n": 19, "ms": 3, "title": "Making it run: inference, measured", "tt": [14, 15, 16, 17, 18, 19], "unlocks": ["06"],
     "goal": "Profile a model, quantize and prune it, fuse and vectorise its hot paths, cache attention keys and values, and benchmark the result with confidence intervals.",
     "why": "Alaap's minimum shippable thing is blocked at the platform track: an inference service over HTTP, and GPU hosting with p95 latency and cost per minute measured under load. These modules are that skill set.",
     "diagram": "serve", "arch": ["stages", "ctx"],
     "check": ("Why does a KV cache make autoregressive generation faster, and what does it cost?",
               "Without it, each new token recomputes keys and values for the whole prefix, so generation is quadratic. The cache stores them and computes only the new token's, making each step linear. The cost is memory per sequence, which grows with length and limits how many users one GPU serves.")},
    {"n": 20, "ms": 3, "title": "The roads not taken", "hours": 6,
     "goal": "Argue about backend choice rather than inherit it: what each rejected system is, why it was rejected, and what would change the answer.",
     "why": "Licences and model shapes decide more of this project than benchmarks do. Five licence chains checked, five mis-declared.",
     "alaap": ["part-7"], "arch": ["backend"],
     "check": ("Why does invariant I4 call a licence declaration a claim, not evidence?",
               "Because derived models inherit their parents' terms, and the declaration on the derived model is often wrong: every one of the five Indic chains checked was mis-declared upstream. Only tracing the chain to the training data is evidence.")},
    {"n": 21, "ms": 3, "title": "Capstone: Alaap, from scratch", "tt": [20],
     "goal": "Put the whole stack together: a model you trained, served and benchmarked, and the five ideas that cost the project longest to learn.",
     "why": "Alaap becomes something you trained rather than an assembly of other people's models.",
     "alaap": ["five-ideas"], "diagram": "owned", "map": "Alaap, from scratch",
     "check": ("A new result is suspiciously good. What do you do first?",
               "Treat it as a bug report about the setup. State the property you expected before reading further, then check the measurement, the corpus and the comparison: the project recorded this about seventeen times, every time.")},
]

# Metadata for the fourteen architecture diagrams. stages are plan stage numbers.
ARCH_META = {
    "ctx": {"involves": ["description", "script", "per-line direction", "mapper", "identity store", "frozen TTS renderer", "gates", "watermark", "per-line audio and manifest"],
            "topics": ["system context", "frozen model", "product contract"], "stages": [0, 21]},
    "tower": {"involves": ["text encoder", "mapper head", "speaker vector", "frozen acoustic LM", "codec decoder", "drift loop"],
              "topics": ["two-tower design", "navigability (E1)", "drift"], "stages": [0, 13, 16]},
    "mint": {"involves": ["bin labels from text", "MiniLM text encoder", "hybrid retrieval", "top_k = 2 SLERP blend", "novelty", "four gates", "IdentityStore"],
             "topics": ["retrieval", "interpolation", "gating", "identity storage"], "stages": [0, 13, 17]},
    "render": {"involves": ["stored identity", "Direction (emotion, rate)", "frozen TTS", "phase vocoder retime", "AudioSeal", "provenance"],
               "topics": ["identity versus performance (I5)", "phase vocoder", "watermarking"], "stages": [0, 16]},
    "gates": {"involves": ["drift", "consistency", "uniqueness", "CER", "naturalness (WavLM layer 7)"],
              "topics": ["calibrated thresholds", "MOS-predictor trap (I9)", "evaluation"], "stages": [0, 18]},
    "rev": {"involves": ["measure() on 17 attributes", "percentile Binner", "captions from bins", "re-measurement", "adherence"],
            "topics": ["measure-first captions", "reversibility", "estimator audits"], "stages": [11, 18]},
    "geom": {"involves": ["raw vectors", "mean-centring", "per-dimension rescale", "PCA basis", "the shell", "SLERP"],
             "topics": ["anisotropy (I1)", "interpolation versus extrapolation", "sparse regions"], "stages": [13]},
    "axes": {"involves": ["f0_mean", "spectral_tilt", "vtl_cm", "dropped and unused attributes"],
             "topics": ["source and filter", "identity axes", "within/between screen"], "stages": [2, 11]},
    "backend": {"involves": ["Renderer protocol", "Qwen3-TTS 1.7B (English)", "Indic-Mio with MioCodec", "vector widths 2048 and 128"],
                "topics": ["backend adapters", "licence enforcement (I3, I4)", "sample rates"], "stages": [16, 20]},
    "codec": {"involves": ["MioCodec encode", "content tokens at 25 Hz", "global embedding (128)", "decode"],
              "topics": ["neural codecs", "FSQ", "content and identity split"], "stages": [16]},
    "dir": {"involves": ["emotion as alpha times tau on the vector", "rate by phase vocoder", "text tags (inert)"],
            "topics": ["per-line direction", "task vectors", "identity stores timbre only"], "stages": [17]},
    "mods": {"involves": ["service", "mapper", "renderer", "identity", "acoustics", "geometry", "metrics", "encoder (ECAPA)", "data", "captions"],
             "topics": ["module boundaries", "the independent judge"], "stages": [12, 21]},
    "exp": {"involves": ["E0 to E15", "S2 to S24", "the ~22-voice wall", "four failed levers"],
            "topics": ["experiment lineage", "negative results", "instrument track"], "stages": [18]},
    "stages": {"involves": ["track A (ML) S0 to S5", "track B (platform) S6 to S10", "minimum shippable thing"],
               "topics": ["plan status", "platform gap", "naming collision"], "stages": [19, 21]},
}

# Diagrams drawn for the plan, in the architecture page's own primitives.
# Grid layout: col and row in cells; cls is b (neutral), b1 blue data/identity,
# b2 amber model, b3 green measurement, b4 plum gate/risk. Edges: ln grey, ln2 blue, ln3 plum.
DIAGRAMS = {
    "sampling": {
        "heads": [(0, "continuous"), (1, "sampled"), (2, "resampled"), (3, "what survives")],
        "nodes": [
            {"id": "wave", "c": 0, "r": 0, "label": "air pressure", "sub": "a continuous wave", "cls": "b"},
            {"id": "s24", "c": 1, "r": 0, "label": "24 kHz corpus", "sub": "24 000 readings a second", "cls": "b1"},
            {"id": "ny", "c": 1, "r": 1, "label": "Nyquist: 12 kHz", "sub": "half the sample rate", "cls": "b3"},
            {"id": "lp", "c": 2, "r": 0, "label": "low-pass, then", "sub": "keep 2 of every 3", "cls": "b2"},
            {"id": "s16", "c": 3, "r": 0, "label": "16 kHz for WavLM", "sub": "content up to 8 kHz", "cls": "b1"},
            {"id": "alias", "c": 3, "r": 1, "label": "without the filter", "sub": "10 kHz folds to 6 kHz", "cls": "b4"},
        ],
        "edges": [("wave", "s24", "sample"), ("s24", "lp", ""), ("lp", "s16", ""), ("s24", "ny", ""), ("lp", "alias", "skip it", "ln3")],
        "caption": "<b>The cliff is the filter.</b> A sample rate can only represent frequencies below half of itself. Resampling down has to remove what no longer fits, or it reappears at the wrong frequency as aliasing."},
    "sourcefilter": {
        "heads": [(0, "source"), (1, "filter"), (2, "what you hear"), (3, "Alaap measures")],
        "nodes": [
            {"id": "folds", "c": 0, "r": 0, "label": "vocal folds", "sub": "a buzz at F0", "cls": "b1"},
            {"id": "tract", "c": 1, "r": 0, "label": "vocal tract", "sub": "a tube with resonances", "cls": "b1"},
            {"id": "speech", "c": 2, "r": 0, "label": "speech", "sub": "buzz shaped by tube", "cls": "b"},
            {"id": "f0", "c": 3, "r": 0, "label": "f0_mean", "sub": "the source", "cls": "b3"},
            {"id": "vtl", "c": 3, "r": 1, "label": "vtl_cm, formants", "sub": "the filter", "cls": "b3"},
            {"id": "tilt", "c": 2, "r": 1, "label": "spectral_tilt", "sub": "meant for source, reads F0", "cls": "b4"},
        ],
        "edges": [("folds", "tract", "excites"), ("tract", "speech", ""), ("speech", "f0", ""), ("speech", "vtl", ""), ("speech", "tilt", "", "ln3")],
        "caption": "<b>Change the buzz and it is the same person; change the tube and it is not.</b> Every identity axis Alaap keeps lands on one side of this split, and the one that straddles it, spectral tilt, is the one that caused trouble."},
    "tensor": {
        "heads": [(0, "data"), (1, "view"), (2, "operation"), (3, "result")],
        "nodes": [
            {"id": "buf", "c": 0, "r": 0, "label": "flat buffer", "sub": "float32, contiguous", "cls": "b"},
            {"id": "shape", "c": 1, "r": 0, "label": "shape + strides", "sub": "(32, 80) · (80, 1)", "cls": "b1"},
            {"id": "t", "c": 1, "r": 1, "label": "transpose", "sub": "same buffer, new strides", "cls": "b1"},
            {"id": "bc", "c": 2, "r": 0, "label": "broadcast add", "sub": "(32, 80) + (80,)", "cls": "b2"},
            {"id": "mm", "c": 2, "r": 1, "label": "matmul", "sub": "(32, 80) @ (80, 256)", "cls": "b2"},
            {"id": "out", "c": 3, "r": 0, "label": "(32, 80)", "sub": "no copy of the (80,)", "cls": "b3"},
            {"id": "out2", "c": 3, "r": 1, "label": "(32, 256)", "sub": "inner dims must match", "cls": "b3"},
        ],
        "edges": [("buf", "shape", ""), ("shape", "t", "view"), ("shape", "bc", ""), ("bc", "out", ""), ("shape", "mm", ""), ("mm", "out2", "")],
        "caption": "<b>A tensor is a buffer plus a way of reading it.</b> Shape and strides decide what an index means, so transpose and view are free, and broadcasting repeats a smaller tensor without copying it."},
    "layer": {
        "heads": [(0, "input"), (1, "parameters"), (2, "no parameters"), (3, "mode-dependent")],
        "nodes": [
            {"id": "x", "c": 0, "r": 0, "label": "x", "sub": "(batch, 784)", "cls": "b1"},
            {"id": "lin", "c": 1, "r": 0, "label": "Linear", "sub": "W (784, 256), b (256)", "cls": "b2"},
            {"id": "relu", "c": 2, "r": 0, "label": "ReLU", "sub": "max(0, z)", "cls": "b"},
            {"id": "drop", "c": 3, "r": 0, "label": "Dropout p = 0.5", "sub": "train: drop, scale x2", "cls": "b4"},
            {"id": "eval", "c": 3, "r": 1, "label": "eval()", "sub": "passes everything", "cls": "b3"},
            {"id": "sm", "c": 2, "r": 1, "label": "softmax (output)", "sub": "subtract the max first", "cls": "b"},
        ],
        "edges": [("x", "lin", ""), ("lin", "relu", ""), ("relu", "drop", ""), ("drop", "eval", "mode", "ln3"), ("relu", "sm", "last layer")],
        "caption": "<b>A layer is parameters plus a rule, and some rules depend on the mode.</b> Linear owns weights; ReLU and softmax own nothing; dropout behaves differently under train() and eval(), which is why Alaap calls eval() before every measurement."},
    "loss": {
        "heads": [(0, "model output"), (1, "probabilities"), (2, "loss"), (3, "gradient")],
        "nodes": [
            {"id": "z", "c": 0, "r": 0, "label": "logits z", "sub": "any real numbers", "cls": "b1"},
            {"id": "p", "c": 1, "r": 0, "label": "softmax", "sub": "p = exp(z - max) / sum", "cls": "b2"},
            {"id": "ce", "c": 2, "r": 0, "label": "cross-entropy", "sub": "-log p[target]", "cls": "b4"},
            {"id": "g", "c": 3, "r": 0, "label": "p - onehot", "sub": "large while wrong", "cls": "b3"},
            {"id": "mse", "c": 2, "r": 1, "label": "sigmoid + MSE", "sub": "the alternative", "cls": "b"},
            {"id": "g2", "c": 3, "r": 1, "label": "vanishes", "sub": "when saturated", "cls": "b4"},
        ],
        "edges": [("z", "p", ""), ("p", "ce", ""), ("ce", "g", "backward", "ln2"), ("mse", "g2", "backward", "ln3")],
        "caption": "<b>Cross-entropy's gradient survives saturation.</b> Paired with softmax, the log cancels the exponential and the gradient is simply p minus the target."},
    "data": {
        "heads": [(0, "stored"), (1, "each epoch"), (2, "each step"), (3, "to the model")],
        "nodes": [
            {"id": "ds", "c": 0, "r": 0, "label": "Dataset", "sub": "__len__, __getitem__", "cls": "b1"},
            {"id": "sh", "c": 1, "r": 0, "label": "shuffle indices", "sub": "a permutation, not data", "cls": "b2"},
            {"id": "bt", "c": 2, "r": 0, "label": "take a batch", "sub": "batch_size indices", "cls": "b2"},
            {"id": "col", "c": 3, "r": 0, "label": "collate", "sub": "stack into one tensor", "cls": "b3"},
            {"id": "mem", "c": 2, "r": 1, "label": "memory per batch", "sub": "batch x sample bytes", "cls": "b4"},
        ],
        "edges": [("ds", "sh", ""), ("sh", "bt", ""), ("bt", "col", ""), ("bt", "mem", "", "ln3")],
        "caption": "<b>Shuffle the indices, not the data.</b> A DataLoader permutes a list of integers, fetches only the batch it needs, and stacks it. The whole dataset never has to fit in memory."},
    "autograd": {
        "heads": [(0, "forward, recorded"), (1, ""), (2, ""), (3, "backward, replayed")],
        "nodes": [
            {"id": "x", "c": 0, "r": 0, "label": "x, W", "sub": "requires_grad", "cls": "b1"},
            {"id": "mm", "c": 1, "r": 0, "label": "MatmulBackward", "sub": "saves x and W", "cls": "b2"},
            {"id": "relu", "c": 2, "r": 0, "label": "ReluBackward", "sub": "saves the mask", "cls": "b2"},
            {"id": "L", "c": 3, "r": 0, "label": "loss", "sub": "loss.backward()", "cls": "b4"},
            {"id": "g3", "c": 3, "r": 1, "label": "grad = 1", "sub": "seed", "cls": "b3"},
            {"id": "g2", "c": 2, "r": 1, "label": "grad x mask", "sub": "chain rule", "cls": "b3"},
            {"id": "g1", "c": 1, "r": 1, "label": "W.grad, x.grad", "sub": "g @ W.T, x.T @ g", "cls": "b3"},
        ],
        "edges": [("x", "mm", ""), ("mm", "relu", ""), ("relu", "L", ""), ("L", "g3", "", "ln2"), ("g3", "g2", "", "ln2"), ("g2", "g1", "", "ln2")],
        "caption": "<b>The graph is a tape recorded on the way forward.</b> Each operation saves what its gradient rule needs; backward() walks the tape in reverse and multiplies by each local derivative. no_grad() stops the recording, which is why it saves memory."},
    "loop": {
        "heads": [(0, ""), (1, "one step"), (2, ""), (3, "")],
        "nodes": [
            {"id": "zg", "c": 0, "r": 0, "label": "zero_grad()", "sub": "clear last step", "cls": "b4"},
            {"id": "fw", "c": 1, "r": 0, "label": "forward", "sub": "model(batch)", "cls": "b2"},
            {"id": "ls", "c": 2, "r": 0, "label": "loss", "sub": "criterion(out, y)", "cls": "b2"},
            {"id": "bw", "c": 3, "r": 0, "label": "backward()", "sub": "fills .grad", "cls": "b3"},
            {"id": "st", "c": 3, "r": 1, "label": "optimizer.step()", "sub": "SGD or Adam update", "cls": "b1"},
            {"id": "sch", "c": 2, "r": 1, "label": "schedule, clip", "sub": "lr decay, global norm", "cls": "b"},
            {"id": "ev", "c": 0, "r": 1, "label": "eval() + no_grad()", "sub": "validate, checkpoint", "cls": "b3"},
        ],
        "edges": [("zg", "fw", ""), ("fw", "ls", ""), ("ls", "bw", ""), ("bw", "st", ""), ("st", "sch", ""), ("sch", "zg", "next batch", "ln2"), ("st", "ev", "each epoch", "ln3")],
        "caption": "<b>Five lines that every training script is.</b> Adam keeps two running averages per parameter, so with the weights it holds three copies, against two for SGD with momentum. Evaluation switches both the layer mode and gradient recording off."},
    "torchmap": {
        "heads": [(0, "you built, in TrenTorch"), (1, ""), (2, "you read, in PyTorch"), (3, "")],
        "nodes": [
            {"id": "a1", "c": 0, "r": 0, "label": "Tensor", "sub": "trentorch.core.tensor", "cls": "b1"},
            {"id": "b1", "c": 2, "r": 0, "label": "torch.Tensor", "sub": ".to(device), dtype", "cls": "b2", "span": 2},
            {"id": "a2", "c": 0, "r": 1, "label": "Function, backward", "sub": "trentorch.core.autograd", "cls": "b1"},
            {"id": "b2", "c": 2, "r": 1, "label": "autograd, no_grad, detach", "sub": "the same tape", "cls": "b2", "span": 2},
            {"id": "a3", "c": 0, "r": 2, "label": "Linear, Dropout", "sub": "trentorch.core.layers", "cls": "b1"},
            {"id": "b3", "c": 2, "r": 2, "label": "nn.Module, eval()", "sub": "parameters vs buffers", "cls": "b2", "span": 2},
            {"id": "a4", "c": 0, "r": 3, "label": "Trainer, DataLoader", "sub": "trentorch.core.training", "cls": "b1"},
            {"id": "b4", "c": 2, "r": 3, "label": "optim, utils.data", "sub": "the loop you wrote", "cls": "b2", "span": 2},
        ],
        "edges": [("a1", "b1", "is"), ("a2", "b2", "is"), ("a3", "b3", "is"), ("a4", "b4", "is")],
        "caption": "<b>Every PyTorch line in Alaap maps to something you built.</b> The differences are devices, dtypes and scale; the mechanism is the one you wrote on NumPy."},
    "conv1d": {
        "heads": [(0, "audio frames"), (1, "TDNN / ECAPA"), (2, "pooling"), (3, "embedding")],
        "nodes": [
            {"id": "mel", "c": 0, "r": 0, "label": "80 mel bands", "sub": "one column per 10 ms", "cls": "b1"},
            {"id": "c1", "c": 1, "r": 0, "label": "Conv1d over time", "sub": "kernel 5, one filter slid", "cls": "b2"},
            {"id": "c2", "c": 1, "r": 1, "label": "dilated Conv1d", "sub": "wider context, same cost", "cls": "b2"},
            {"id": "bn", "c": 0, "r": 1, "label": "BatchNorm", "sub": "per channel", "cls": "b"},
            {"id": "pool", "c": 2, "r": 0, "label": "attentive stats", "sub": "weighted mean and std", "cls": "b3"},
            {"id": "emb", "c": 3, "r": 0, "label": "fixed-length vector", "sub": "any length in, one out", "cls": "b1"},
        ],
        "edges": [("mel", "c1", ""), ("c1", "c2", ""), ("c2", "bn", "", "ln"), ("c2", "pool", ""), ("pool", "emb", "")],
        "caption": "<b>ECAPA-TDNN is convolution along time.</b> The same small filter slides over frames of audio, dilation widens what it sees, and pooling over time turns an utterance of any length into one vector."},
    "stft": {
        "heads": [(0, "waveform"), (1, "one window"), (2, "one column"), (3, "the picture")],
        "nodes": [
            {"id": "w", "c": 0, "r": 0, "label": "samples", "sub": "24 kHz", "cls": "b1"},
            {"id": "win", "c": 1, "r": 0, "label": "n_fft = 2048", "sub": "85 ms, Hann window", "cls": "b2"},
            {"id": "fft", "c": 2, "r": 0, "label": "FFT", "sub": "1025 bins, 11.7 Hz each", "cls": "b2"},
            {"id": "spec", "c": 3, "r": 0, "label": "spectrogram", "sub": "time x frequency", "cls": "b3"},
            {"id": "hop", "c": 1, "r": 1, "label": "hop = 512", "sub": "slide 21 ms, repeat", "cls": "b"},
            {"id": "trade", "c": 3, "r": 1, "label": "the trade", "sub": "long window: sharp Hz, blurry time", "cls": "b4"},
        ],
        "edges": [("w", "win", ""), ("win", "fft", ""), ("fft", "spec", ""), ("hop", "win", "", "ln2"), ("spec", "trade", "", "ln3")],
        "caption": "<b>The STFT is an FFT on a sliding window.</b> Every parameter is a trade between time and frequency resolution, and both numbers appear inside spectral_tilt."},
    "xvector": {
        "heads": [(0, "train"), (1, ""), (2, ""), (3, "keep")],
        "nodes": [
            {"id": "utt", "c": 0, "r": 0, "label": "utterance", "sub": "thousands of speakers", "cls": "b1"},
            {"id": "enc", "c": 1, "r": 0, "label": "ECAPA-TDNN", "sub": "conv + pooling", "cls": "b2"},
            {"id": "emb", "c": 2, "r": 0, "label": "penultimate layer", "sub": "a fixed-length vector", "cls": "b1"},
            {"id": "cls", "c": 3, "r": 0, "label": "speaker classifier", "sub": "thrown away", "cls": "b4"},
            {"id": "cos", "c": 2, "r": 1, "label": "cosine(a, b)", "sub": "same or different?", "cls": "b3"},
            {"id": "thr", "c": 3, "r": 1, "label": "in-domain calibration", "sub": "C_same 0.70, C_diff 0.20", "cls": "b3"},
        ],
        "edges": [("utt", "enc", ""), ("enc", "emb", ""), ("emb", "cls", "training only", "ln3"), ("emb", "cos", ""), ("cos", "thr", "")],
        "caption": "<b>Train to tell speakers apart, then drop the classifier.</b> The layer before it is the embedding, and it inherits whatever training made it ignore: channel and quality. That is why it judges identity and never quality."},
    "embed": {
        "heads": [(0, "text"), (1, "tokens"), (2, "lookup"), (3, "into the model")],
        "nodes": [
            {"id": "txt", "c": 0, "r": 0, "label": "\"warm voice\"", "sub": "characters", "cls": "b1"},
            {"id": "tok", "c": 1, "r": 0, "label": "BPE tokenizer", "sub": "ids [812, 4431]", "cls": "b2"},
            {"id": "tab", "c": 2, "r": 0, "label": "embedding table", "sub": "(vocab, d) weights", "cls": "b2"},
            {"id": "pos", "c": 2, "r": 1, "label": "+ position", "sub": "learned or sinusoidal", "cls": "b"},
            {"id": "vec", "c": 3, "r": 0, "label": "(tokens, d)", "sub": "one row per token", "cls": "b1"},
            {"id": "audio", "c": 0, "r": 1, "label": "audio, via a codec", "sub": "25 Hz content tokens", "cls": "b3"},
        ],
        "edges": [("txt", "tok", ""), ("tok", "tab", "row index"), ("tab", "vec", ""), ("pos", "vec", "add"), ("audio", "tok", "same idea", "ln2")],
        "caption": "<b>An embedding is a row of a weight matrix.</b> A token id picks the row; gradient descent wrote the numbers. A codec does for audio what the tokenizer does for text, which is why TTS can be a language model."},
    "attention": {
        "heads": [(0, "input"), (1, "projections"), (2, "scores"), (3, "output")],
        "nodes": [
            {"id": "x", "c": 0, "r": 0, "label": "x", "sub": "(n, d)", "cls": "b1"},
            {"id": "q", "c": 1, "r": 0, "label": "Q = x Wq", "sub": "what I look for", "cls": "b2"},
            {"id": "k", "c": 1, "r": 1, "label": "K = x Wk", "sub": "what I offer", "cls": "b2"},
            {"id": "v", "c": 1, "r": 2, "label": "V = x Wv", "sub": "what I pass on", "cls": "b2"},
            {"id": "s", "c": 2, "r": 0, "label": "Q K^T / sqrt(d_k)", "sub": "(n, n): the O(n^2)", "cls": "b4"},
            {"id": "sm", "c": 2, "r": 1, "label": "mask, softmax", "sub": "rows sum to 1", "cls": "b3"},
            {"id": "o", "c": 3, "r": 1, "label": "weights @ V", "sub": "(n, d), per head", "cls": "b1"},
        ],
        "edges": [("x", "q", ""), ("x", "k", ""), ("x", "v", ""), ("q", "s", ""), ("k", "s", ""), ("s", "sm", ""), ("sm", "o", ""), ("v", "o", "")],
        "caption": "<b>Every token scores every other token.</b> The n by n score matrix is where attention's quadratic memory comes from, and the square root of d_k keeps those scores out of softmax's flat tails."},
    "ttslm": {
        "heads": [(0, "in"), (1, "frozen acoustic LM"), (2, "codec"), (3, "out")],
        "nodes": [
            {"id": "txt", "c": 0, "r": 0, "label": "text tokens", "sub": "what to say", "cls": "b1"},
            {"id": "spk", "c": 0, "r": 1, "label": "speaker vector", "sub": "who says it", "cls": "b1"},
            {"id": "lm", "c": 1, "r": 0, "label": "transformer", "sub": "predicts codec tokens", "cls": "b2"},
            {"id": "tok", "c": 2, "r": 0, "label": "content tokens", "sub": "FSQ [8,8,8,5,5]", "cls": "b3"},
            {"id": "dec", "c": 2, "r": 1, "label": "codec decoder", "sub": "tokens + identity", "cls": "b2"},
            {"id": "wav", "c": 3, "r": 1, "label": "waveform", "sub": "44.1 kHz", "cls": "b1"},
        ],
        "edges": [("txt", "lm", ""), ("spk", "lm", "", "ln2"), ("lm", "tok", ""), ("tok", "dec", ""), ("spk", "dec", "", "ln2"), ("dec", "wav", "")],
        "caption": "<b>Once audio is integers, a language model can write it.</b> Content tokens are generated once and decoded through any speaker vector, which is why forty voices cost the same language-model time as one."},
    "mdn": {
        "heads": [(0, "description"), (1, "encoder"), (2, "MDN head"), (3, "speaker space")],
        "nodes": [
            {"id": "d", "c": 0, "r": 0, "label": "\"a warm low voice\"", "sub": "free text", "cls": "b1"},
            {"id": "e", "c": 1, "r": 0, "label": "sentence encoder", "sub": "MiniLM", "cls": "b2"},
            {"id": "m", "c": 2, "r": 0, "label": "10 Gaussians", "sub": "weights, means, spreads", "cls": "b2"},
            {"id": "s", "c": 3, "r": 0, "label": "sample a vector", "sub": "a family, not a point", "cls": "b1"},
            {"id": "loss", "c": 2, "r": 1, "label": "negative log-likelihood", "sub": "of the real speaker", "cls": "b4"},
            {"id": "reg", "c": 3, "r": 1, "label": "a plain regressor", "sub": "predicts the blurred mean", "cls": "b"},
        ],
        "edges": [("d", "e", ""), ("e", "m", ""), ("m", "s", "sample"), ("m", "loss", "train", "ln3")],
        "caption": "<b>One description, many valid voices.</b> A mixture density network outputs a distribution over speaker vectors and is trained by the likelihood of the real one; a regressor would average them into one central voice."},
    "vendi": {
        "heads": [(0, "voices"), (1, "similarity"), (2, "spectrum"), (3, "the number")],
        "nodes": [
            {"id": "v", "c": 0, "r": 0, "label": "n voices", "sub": "speaker vectors", "cls": "b1"},
            {"id": "k", "c": 1, "r": 0, "label": "similarity matrix", "sub": "(n, n), cosine", "cls": "b2"},
            {"id": "eig", "c": 2, "r": 0, "label": "eigenvalues", "sub": "normalised to sum 1", "cls": "b2"},
            {"id": "ent", "c": 3, "r": 0, "label": "exp(entropy)", "sub": "effective voices", "cls": "b3"},
            {"id": "trap", "c": 3, "r": 1, "label": "the trap", "sub": "a fraction of n is not a count", "cls": "b4"},
        ],
        "edges": [("v", "k", ""), ("k", "eig", ""), ("eig", "ent", ""), ("ent", "trap", "", "ln3")],
        "caption": "<b>Vendi counts distinct things.</b> Forty voices that are really twenty distinct ones score about twenty. Normalised Vendi divides by n, so the same fraction over different set sizes means different counts."},
    "serve": {
        "heads": [(0, "measure"), (1, "shrink"), (2, "speed up"), (3, "prove")],
        "nodes": [
            {"id": "p", "c": 0, "r": 0, "label": "profile", "sub": "FLOPs, memory, where time goes", "cls": "b3"},
            {"id": "q", "c": 1, "r": 0, "label": "quantize", "sub": "float32 to int8, x4 smaller", "cls": "b2"},
            {"id": "c", "c": 1, "r": 1, "label": "prune, distil", "sub": "fewer weights", "cls": "b2"},
            {"id": "a", "c": 2, "r": 0, "label": "fuse, vectorise", "sub": "fewer memory trips", "cls": "b2"},
            {"id": "kv", "c": 2, "r": 1, "label": "KV cache", "sub": "reuse past keys, values", "cls": "b1"},
            {"id": "b", "c": 3, "r": 0, "label": "benchmark", "sub": "p95 latency, CI", "cls": "b3"},
            {"id": "alaap", "c": 3, "r": 1, "label": "Alaap S6, S7", "sub": "over HTTP, $/min", "cls": "b4"},
        ],
        "edges": [("p", "q", ""), ("q", "a", ""), ("p", "c", ""), ("c", "kv", ""), ("a", "b", ""), ("kv", "b", ""), ("b", "alaap", "", "ln3")],
        "caption": "<b>Measure, shrink, speed up, prove.</b> Alaap's platform track is blocked on exactly this: a service that renders over HTTP, hosted with its p95 latency and cost per minute measured under load."},
    "owned": {
        "heads": [(0, "in"), (1, "what you built it from"), (2, ""), (3, "out")],
        "nodes": [
            {"id": "d", "c": 0, "r": 0, "label": "description", "sub": "stage 14: tokens", "cls": "b1"},
            {"id": "m", "c": 1, "r": 0, "label": "mapper (MDN)", "sub": "stages 5, 8, 17", "cls": "b2"},
            {"id": "id", "c": 1, "r": 1, "label": "identity store", "sub": "stage 13: the shell", "cls": "b4"},
            {"id": "r", "c": 2, "r": 0, "label": "frozen TTS", "sub": "stages 15, 16", "cls": "b2"},
            {"id": "g", "c": 2, "r": 1, "label": "gates", "sub": "stages 12, 18", "cls": "b3"},
            {"id": "s", "c": 3, "r": 0, "label": "service over HTTP", "sub": "stage 19", "cls": "b1"},
            {"id": "a", "c": 3, "r": 1, "label": "audio, per line", "sub": "stages 1, 2, 11", "cls": "b1"},
        ],
        "edges": [("d", "m", ""), ("m", "id", ""), ("id", "r", "", "ln2"), ("r", "g", ""), ("g", "a", ""), ("r", "s", "")],
        "caption": "<b>Every box, and the stage that taught it.</b> The system context from stage 0, again, except that now you can say how each part works because you built or read every one."},
}
