"""Keep Accelerate's links into ALAAP.html in step with the plan.

Rewrites the block between /* AL:BEGIN */ and /* AL:END */ in index.html: the
stage list the tracker shows on "What comes after", and the label for every anchor
a pointer or map node can name. Called by build.py after it writes ALAAP.html, so
the page and the tracker are generated from the same plan.py.
"""
import io, json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
INDEX = os.path.join(os.path.dirname(HERE), "index.html")


def labels(plan, pieces_parts, arch_titles):
    out = {}
    for s in plan.STAGES:
        short = s["title"].split(":")[0]
        out["plan/stage-%d" % s["n"]] = "Stage %d, %s" % (s["n"], short)
        for a in s.get("alaap", []):
            if a.startswith("s"):
                out["plan/" + a] = "Stage %d, %s (guide %s)" % (s["n"], short, a[1:].replace("-", "."))
            elif a.startswith("part-"):
                out["plan/" + a] = "Stage %d, %s (guide Part %s)" % (s["n"], short, a.split("-")[1])
            else:
                out["plan/" + a] = "Stage %d, %s" % (s["n"], short)
    for fid, title in arch_titles.items():
        out["architecture/" + fid] = "Architecture " + re.sub(r"<[^>]+>", "", title).replace(" · ", ", ")
    out["status"] = "Where Alaap stands"
    out["accent"] = "Accent and rights"
    return out


def wire(plan, arch_titles):
    src = io.open(INDEX, encoding="utf-8").read()
    a, b = src.find("/* AL:BEGIN */"), src.find("/* AL:END */")
    if a < 0 or b < 0:
        sys.exit("index.html has no AL:BEGIN / AL:END markers")
    stages = [[s["n"], s["ms"], s["title"]] for s in plan.STAGES]
    block = ("/* AL:BEGIN */\n  /* Generated by alaap/build.py from alaap/plan.py; do not edit by hand.\n"
             "     Pointers are { p: \"<tab>/<anchor>\", why } on steps, and al: \"<tab>/<anchor>\" on map nodes. */\n"
             "  var AL = {\n    file: \"ALAAP.html\",\n    stages: %s,\n    labels: %s\n  };\n  "
             % (json.dumps(stages, ensure_ascii=False), json.dumps(labels(plan, None, arch_titles), ensure_ascii=False, indent=6)[:-1] + "    }"))
    src = src[:a] + block + src[b:]
    io.open(INDEX, "w", encoding="utf-8", newline="").write(src)
    return len(stages)
