"""Fetch the system design guide's three typefaces for offline use.

Reads the Google Fonts stylesheet saved as google.css, keeps the latin and
latin-ext faces, downloads each woff2 once, and writes fonts.css pointing at the
local copies, relative to this folder. Re-run after changing the families in google.css:

    python fonts/fetch.py
"""
import os, re, urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
css = open(os.path.join(HERE, "google.css"), encoding="utf-8").read()
blocks = re.findall(r"/\* ([\w-]+) \*/\s*(@font-face \{.*?\})", css, re.S)
out, fetched = [], {}
for subset, block in blocks:
    if subset not in ("latin", "latin-ext"):
        continue
    family = re.search(r"font-family: '([^']+)'", block).group(1)
    weight = re.search(r"font-weight: (\d+)", block).group(1)
    url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)
    if url not in fetched:
        name = "%s-%s-%s.woff2" % (family.replace(" ", ""), weight, subset)
        path = os.path.join(HERE, name)
        if not os.path.exists(path):
            urllib.request.urlretrieve(url, path)
        fetched[url] = name
    out.append(block.replace(url, fetched[url]).replace("\n  ", "\n  "))
open(os.path.join(HERE, "fonts.css"), "w", encoding="utf-8", newline="\n").write(
    "/* Generated by fonts/fetch.py from google.css. Latin and latin-ext only. */\n" + "\n".join(out) + "\n")
print(len(out), "faces,", len(fetched), "files")
